version: '3'
services:

    loader:
        container_name: globomap_loader
        build:
            context: ./
            dockerfile: scripts/docker/Dockerfile_loader
        env_file:
            - ./scripts/docker/globomap.env
        volumes:
            - .:/app
        networks:
            - globomap-api_globomap_net
        command: sh ./scripts/docker/docker-start-loader.sh
        depends_on:
            - db
            - queue
        external_links:
            - globomap_api
            - db:globomap_loader_db_mysql
            - queue:globomap_loader_queue

networks:
    globomap-api_globomap_net:
        external: true

volumes:
    globomap_loader_db_vol:
